# Single-command dev and ops. Install just: `brew install just`.

default:
  @just --list

# ────────── dev ──────────

infra-up:
  docker compose -f infra/docker-compose.yml up -d postgres minio mailpit nats

infra-down:
  docker compose -f infra/docker-compose.yml down

obs-up:
  docker compose -f infra/docker-compose.yml -f infra/docker-compose.observability.yml up -d

backend-dev:
  cd backend && cargo watch -x run

frontend-dev:
  cd frontend && bun run dev

# ────────── build ──────────

backend-build:
  cd backend && cargo build --release --locked

backend-image tag="dev":
  DOCKER_BUILDKIT=1 docker build -t simu-backend:{{tag}} -f backend/Dockerfile backend

frontend-build:
  cd frontend && bun run build

# ────────── test ──────────

backend-test:
  cd backend && cargo nextest run --all-features

e2e:
  cd frontend && bun run openapi:codegen && bunx playwright test

visual-update:
  cd frontend && bunx playwright test e2e/visual.spec.ts --update-snapshots

# ────────── quality ──────────

lint:
  cd backend && cargo clippy --all-targets --locked -- -D warnings
  cd backend && cargo fmt --all -- --check

audit:
  cd backend && cargo audit
  cd backend && cargo deny check --config deny.toml
  cd backend && cargo machete

# Chase upstream: bump every Rust pin + TS package to latest (spike policy).
# Opens a PR if gh is available; otherwise leaves the commit on a local branch.
deps-bump:
  #!/usr/bin/env bash
  set -eu
  branch="simu/deps-$(date -u +%Y%m%dT%H%M%SZ)"
  git checkout -b "$branch"
  cd backend
  # Keep MSRV in sync with rolling rust:alpine so cargo-edit doesn't silently
  # refuse to bump crates that require a newer rustc.
  bash scripts/sync-msrv.sh
  # Safety: snapshot semver pins; abort if any pin got downgraded.
  grep -oE '^[a-z_-]+ = "=[0-9.]+' Cargo.toml | sort > /tmp/simu-pins-before
  cargo upgrade --incompatible --pinned
  grep -oE '^[a-z_-]+ = "=[0-9.]+' Cargo.toml | sort > /tmp/simu-pins-after
  if diff /tmp/simu-pins-before /tmp/simu-pins-after | grep -qE "^<"; then
    echo "FAIL: cargo-edit downgraded pins:" >&2
    diff /tmp/simu-pins-before /tmp/simu-pins-after | grep -E "^[<>]" >&2
    echo "Likely cause: rust-version MSRV too low for latest crate. Bump rust-version in Cargo.toml." >&2
    exit 1
  fi
  cargo clippy --all-targets --locked -- -D warnings
  cargo deny check
  cd ../frontend && rm -f bun.lock && bun install
  cd ..
  git add -A
  git commit -m "chore(deps): weekly upstream bump (Rust pins + TS latest)"
  if command -v gh >/dev/null 2>&1; then
    git push -u origin "$branch"
    gh pr create --title "chore(deps): weekly upstream bump" \
                 --body "Generated by \`just deps-bump\`. Review breaking changes, then merge." \
                 --fill
  else
    echo "gh not installed; branch $branch kept local — push manually."
  fi

secret-scan:
  gitleaks detect --source=. --no-banner --no-git --config=.gitleaks.toml

trivy:
  trivy image --severity HIGH,CRITICAL --no-progress simu-backend:dev

sbom:
  docker save simu-backend:rolling -o /tmp/simu-backend.tar
  syft /tmp/simu-backend.tar -o spdx-json=docs/SBOM.spdx.json
  rm -f /tmp/simu-backend.tar
  cd backend && cargo cyclonedx --format json --spec-version 1.5
  mv backend/simu-backend.cdx.json docs/SBOM.cdx.json

load:
  SIMU_BASE=http://127.0.0.1:8088 k6 run ops/load.k6.js

# ────────── admin ──────────

# Create an admin user: just admin-create you@example.com s3cret
admin-create email password:
  cd backend && DATABASE_URL=$(grep ^DATABASE_URL .env | cut -d= -f2-) \
    cargo run --bin simu-admin -- create --email {{email}} --password {{password}}

# Promote an existing user to admin: just admin-promote you@example.com
admin-promote email:
  cd backend && DATABASE_URL=$(grep ^DATABASE_URL .env | cut -d= -f2-) \
    cargo run --bin simu-admin -- promote --email {{email}}

# Seed demo data for manual UI testing (admin + 3 users + 1 org + 18 files).
seed:
  bash backend/scripts/seed.sh

# End-to-end backup+restore verification (pg_dump → minio → restore → diff counts).
backup-restore-e2e:
  S3_BUCKET=simu-uploads bash backend/scripts/backup-restore-e2e.sh

# ────────── all ──────────

ci:
  just lint
  just backend-test
  just frontend-build
  just e2e
  just audit
  just secret-scan
